before_script:
  - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:
  - build
  - deploy

build_image:
  stage: build
  image: registry.gitlab.com/dialix1/dialix-back-end:docker
  before_script:
    - apk update && apk add git
    - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
  script: |
      [[ $CI_COMMIT_REF_NAME = 'main' ]] && IMAGE_TAG="$CI_PIPELINE_IID" || IMAGE_TAG="$CI_PIPELINE_IID-dev"
      echo Docker image tag is $IMAGE_TAG
      make build-image TAG=$IMAGE_TAG SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest
      make push-image TAG=$IMAGE_TAG SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest
  only:
    - main
    - dev

deploy_image_prod:
  image: registry.gitlab.com/dialix1/dialix-back-end:docker
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa 34.141.76.50 >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - echo "$GITLAB_PRIVATE_KEY" > ~/.ssh/id_rsa
    - echo "$CI_REGISTRY"
  script: |
      [[ $CI_COMMIT_REF_NAME = 'main' ]] && IMAGE_TAG="$CI_PIPELINE_IID" || IMAGE_TAG="$CI_PIPELINE_IID-dev"
      [[ $CI_COMMIT_REF_NAME = 'main' ]] && SERVICE_POSTFIX="" || SERVICE_POSTFIX="-dev"
      ssh -o StrictHostKeyChecking=no -tt root@34.141.76.50 "sed -i '/registry.gitlab.com/c\\\"$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$IMAGE_TAG\\\" \\\\' /etc/systemd/system/docker-web.service && systemctl daemon-reload && systemctl restart docker-web$SERVICE_POSTFIX"
      # ssh -o StrictHostKeyChecking=no -tt root@34.159.44.81 "sed -i '/registry.gitlab.com/c\\\"$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_IID\ "  ' /etc/systemd/system/docker-web.service && systemctl daemon-reload && systemctl restart docker-web"
      ssh -o StrictHostKeyChecking=no -tt root@34.141.76.50 "sed -i '/registry.gitlab.com/c\\\"$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$IMAGE_TAG\\\" \\\\'   /etc/systemd/system/docker-api-worker.service && systemctl daemon-reload && systemctl restart docker-api-worker$SERVICE_POSTFIX"
      ssh -o StrictHostKeyChecking=no -tt root@34.141.76.50 "sed -i '/registry.gitlab.com/c\\\"$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$IMAGE_TAG\\\" \\\\' /etc/systemd/system/docker-data-worker.service && systemctl daemon-reload && systemctl restart docker-data-worker$SERVICE_POSTFIX"
  only:
    - main
    - dev