before_script:
  - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:
  - build
  - deploy

build_image:
  stage: build
  image: registry.gitlab.com/dialix1/dialix-back-end:docker
  before_script:
    - apk update && apk add git
    - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
  script:
    - make build-image TAG=$CI_PIPELINE_IID SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest
    - make push-image TAG=$CI_PIPELINE_IID SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest
  only:
    - main

deploy_image_prod:
  image: registry.gitlab.com/dialix1/dialix-back-end:docker
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa 34.89.199.177 >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - echo "$GITLAB_PRIVATE_KEY" > ~/.ssh/id_rsa
  script:
    #- ssh -o StrictHostKeyChecking=no -tt root@34.89.199.177 'sed -i `s~"$CI_REGISTRY"~"$CI_REGISTRY"/"$CI_PROJECT_NAMESPACE"/"$CI_PROJECT_NAME":"$CI_PIPELINE_IID"~g` /etc/systemd/system/docker-web.service && systemctl daemon-reload && systemctl restart docker-web'
    - ssh -o StrictHostKeyChecking=no -tt root@34.89.199.177 "sed -i 's~\$CI_REGISTRY~\$CI_REGISTRY/\$CI_PROJECT_NAMESPACE/\$CI_PROJECT_NAME:\$CI_PIPELINE_IID~g' /etc/systemd/system/docker-web.service && systemctl daemon-reload && systemctl restart docker-web"
  only:
  only:
    - main
