before_script:
  - docker login $CI_REGISTRY --username $DEPLOY_TOKEN_USERNAME --password $DEPLOY_TOKEN_PASSWORD

stages:
  - build
  - deploy

build_image:
  stage: build
  image: registry.gitlab.com/dialix1/dialix-back-end:docker
  before_script:
    - apk update && apk add git
    - docker login $CI_REGISTRY --username $DEPLOY_TOKEN_USERNAME --password $DEPLOY_TOKEN_PASSWORD
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
  script: |
      [[ $CI_COMMIT_REF_NAME = 'main' ]] && SERVICE_POSTFIX="" || SERVICE_POSTFIX="-dev"
      [[ $CI_COMMIT_REF_NAME = 'main' ]] && IMAGE_TAG="$CI_PIPELINE_IID" || IMAGE_TAG="$CI_PIPELINE_IID-dev"

      echo Docker image tag is $IMAGE_TAG
      echo Postfix is $SERVICE_POSTFIX

      make build-image TAG=$IMAGE_TAG SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest$SERVICE_POSTFIX
      make push-image TAG=$IMAGE_TAG SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest$SERVICE_POSTFIX
  only:
    - main
    - dev

deploy_image_prod:
  image: registry.gitlab.com/dialix1/dialix-back-end:docker
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa 35.246.192.46 >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - echo "$GITLAB_PRIVATE_KEY" > ~/.ssh/id_rsa
    - echo "$CI_REGISTRY"
  script: |
      SERVER_IP="35.246.192.46"

      [[ $CI_COMMIT_REF_NAME = 'main' ]] && SERVICE_POSTFIX="" || SERVICE_POSTFIX="-dev"
      [[ $CI_COMMIT_REF_NAME = 'main' ]] && IMAGE_TAG="$CI_PIPELINE_IID" || IMAGE_TAG="$CI_PIPELINE_IID-dev"

      ssh -o StrictHostKeyChecking=no -tt root@$SERVER_IP "sed -i '/registry.gitlab.com/c\\\"$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$IMAGE_TAG\\\" \\\\' /etc/systemd/system/docker-web$SERVICE_POSTFIX.service && systemctl daemon-reload && systemctl restart docker-web$SERVICE_POSTFIX"
      ssh -o StrictHostKeyChecking=no -tt root@$SERVER_IP "sed -i '/registry.gitlab.com/c\\\"$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$IMAGE_TAG\\\" \\\\'   /etc/systemd/system/docker-api-worker$SERVICE_POSTFIX.service && systemctl daemon-reload && systemctl restart docker-api-worker$SERVICE_POSTFIX"
      ssh -o StrictHostKeyChecking=no -tt root@$SERVER_IP "sed -i '/registry.gitlab.com/c\\\"$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$IMAGE_TAG\\\" \\\\' /etc/systemd/system/docker-data-worker$SERVICE_POSTFIX.service && systemctl daemon-reload && systemctl restart docker-data-worker$SERVICE_POSTFIX"
  only:
    - main
    - dev