"""create-pbx-bitrix-credential-models

Revision ID: 093bc905877a
Revises: e17dba209cd5
Create Date: 2024-11-19 16:31:53.359238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "093bc905877a"
down_revision: Union[str, None] = "e17dba209cd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bitrix_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("webhook_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("webhook_url"),
    )
    op.create_table(
        "pbx_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pbx_credentials")
    op.drop_table("bitrix_credentials")
    # ### end Alembic commands ###
