"""add-client-phone-number-to-record

Revision ID: 0e18d7dff4f1
Revises: 24c418fbaff6
Create Date: 2024-11-07 15:41:47.092199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e18d7dff4f1'
down_revision: Union[str, None] = '24c418fbaff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('client_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'client_phone_number')
    # ### end Alembic commands ###
