"""set-default-on-blacklist

Revision ID: 24c418fbaff6
Revises: e54dcdea545e
Create Date: 2024-11-06 19:16:39.956236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24c418fbaff6"
down_revision: Union[str, None] = "e54dcdea545e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
