"""create-pbx-call-table

Revision ID: 3f8d0342fa26
Revises: f68b49a43801
Create Date: 2024-12-13 16:52:09.997809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f8d0342fa26"
down_revision: Union[str, None] = "f68b49a43801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pbx_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=False),
        sa.Column("caller_id_name", sa.String(), nullable=True),
        sa.Column("caller_id_number", sa.String(), nullable=True),
        sa.Column("destination_number", sa.String(), nullable=True),
        sa.Column("start_stamp", sa.Integer(), nullable=True),
        sa.Column("end_stamp", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("user_talk_time", sa.Integer(), nullable=True),
        sa.Column("call_type", sa.String(), nullable=True),
        sa.Column("bitrix_result", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pbx_calls")
    # ### end Alembic commands ###
