"""add-unique-constraint-to-bitrix-and-pbx

Revision ID: 66e158925b75
Revises: 87e5daa37700
Create Date: 2024-11-19 22:54:05.822213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66e158925b75"
down_revision: Union[str, None] = "87e5daa37700"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "bitrix_credentials", ["owner_id"])
    op.create_unique_constraint(None, "pbx_credentials", ["owner_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pbx_credentials", type_="unique")
    op.drop_constraint(None, "bitrix_credentials", type_="unique")
    # ### end Alembic commands ###
