"""set-process-bit-for-pbx-call-table

Revision ID: 756a5e6ef826
Revises: bee0df99512f
Create Date: 2024-12-14 01:46:43.525576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "756a5e6ef826"
down_revision: Union[str, None] = "bee0df99512f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pbx_calls", sa.Column("was_processed_from_bitrix", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pbx_calls", "was_processed_from_bitrix")
    # ### end Alembic commands ###
