"""add-key-key-id-on-pbx-credentials

Revision ID: 87e5daa37700
Revises: 093bc905877a
Create Date: 2024-11-19 18:40:21.309490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87e5daa37700"
down_revision: Union[str, None] = "093bc905877a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pbx_credentials", sa.Column("key", sa.String(), nullable=True))
    op.add_column("pbx_credentials", sa.Column("key_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pbx_credentials", "key_id")
    op.drop_column("pbx_credentials", "key")
    # ### end Alembic commands ###
