"""make-title-on-checklist-unique

Revision ID: 9ff4d1f8bf87
Revises: 086559dbda67
Create Date: 2024-11-08 19:07:01.461855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ff4d1f8bf87"
down_revision: Union[str, None] = "086559dbda67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "checklist", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "checklist", type_="unique")
    # ### end Alembic commands ###
