"""make-operator-code-name-call-type-phone-number-nullable

Revision ID: e17dba209cd5
Revises: 9ff4d1f8bf87
Create Date: 2024-11-16 14:32:19.934636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e17dba209cd5"
down_revision: Union[str, None] = "9ff4d1f8bf87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
