"""add-blacklist_token

Revision ID: e54dcdea545e
Revises: 0aac3f7713e3
Create Date: 2024-11-06 11:48:17.903051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e54dcdea545e"
down_revision: Union[str, None] = "0aac3f7713e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("value", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blacklist_token")
    # ### end Alembic commands ###
