"""remove-unique-constraint-on-checklist-title

Revision ID: f68b49a43801
Revises: 77f33ed8af47
Create Date: 2024-11-24 23:39:09.399966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f68b49a43801"
down_revision: Union[str, None] = "77f33ed8af47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("checklist_title_key", "checklist", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("checklist_title_key", "checklist", ["title"])
    # ### end Alembic commands ###
